### ISSUE TITLE
Remove printed header and footer

### ISSUE THREAD

**Issue by Bigben83** [DaanDeSmedt/PHPHeadlessChrome#10]
is there some argument that can be added to remove the printed header and footer information on the pdf, like the date at the top and the url at the bottom.

**Comment by aGeNET** [comment]
Headers/Footers can be disabled by passing parameter`--print-to-pdf-no-header` to the commands.
Works for me with Chrome 84.

**Comment by DaanDeSmedt** [comment]
Added `disablePDFHeader()` in release [PHPHeadlessChrome v1.1.0].(https://github.com/DaanDeSmedt/PHPHeadlessChrome/releases/tag/v1.1.0)
