### ISSUE TITLE
support for in page navigation and click() events?

### ISSUE THREAD

**Issue by menriquez** [DaanDeSmedt/PHPHeadlessChrome#13]
hello...thank you for this nice library.
 
i am trying to build a spider to pull as-near-perfect-as-possible website mirrors for potential legal actions (scam websites and the like) and i have found i need the ability to automate the finding and clicking of javascript-based buttons on the pages...i've looked and don't see that functionality anywhere in the examples.

I like the fact that this lib is build in PHP and not node.js (i will use Puppeteer if necessary but am exploring options before diving into that)  and i know headless chrome supports in-page navigation and click actions...any chance you already support them too or plan on adding that in the future?

**Comment by DaanDeSmedt** [comment]
Hi Menriquez,

This library does not provide high-level control to the Headless Chrome instance as Puppeteer does. 
I would suggest looking into [https://github.com/nesk/puphpeteer](https://github.com/nesk/puphpeteer) when control to the Headless Chrome instance is a requirement. 

Good luck.
