### ISSUE TITLE
Issue with mac os

### ISSUE THREAD

**Issue by Albot15** [DaanDeSmedt/PHPHeadlessChrome#16]
Hi,

I am using chrome version 84 on my MacBook and when I export pdf it exports blank pdf with header and footer. Even I used no header footer tag, still, it prints header and footer and the rest page is blank. I went ahead and downloaded the older version of chrome 71 and it works (it exporting webpage perfectly). However, here also screen size, no footer header tags won't work. 

Can anyone help me here, please?

**Comment by VKupliauskis** [comment]
Its not just mac issue. I'm having this issue, but only some of the time.

I found that using a bigger --virtual-time-budget attribute option, while making it respond slower, made the issue go away. I'm assuming right now toPDF expects the response to be instant rather than waiting for the chrome to wait rendering.

I'm currently using 100000 as my virtual time budget

**Comment by DaanDeSmedt** [comment]
Hi @drajvat ,

As @VKupliauskis mentioned above you can make use of the `--virtual-time-budget ` argument to specify the number of virtual milliseconds to mark the loaded page as 'ready'.


**[virtual-time-budget](https://source.chromium.org/chromium/chromium/src/+/master:headless/app/headless_shell_switches.cc;l=117)**
> If set the system waits the specified number of virtual milliseconds before deeming the page to be ready.
> For determinism virtual time does not advance while there are pending network fetches (i.e no timers will fire). 
> Once all network fetches have completed, timers fire and if the system runs out of virtual time is fastforwarded so the next timer fires immediatley, until the specified virtual time budget is exhausted.
> 


Use the `setArgument` method to specify time budget.

```
$headlessChromer = new HeadlessChrome();
$headlessChromer->setUrl('http://www.google.be');
$headlessChromer->setArgument('--virtual-time-budget', 1000);
$headlessChromer->toPDF('output.pdf');
```

Does that solve your issue?

**Comment by VKupliauskis** [comment]
While this helped for me, i have to make the virtual time budget something of a ridiculous number, reducing performance significantly. I'm not sure if there is something wrong with the way the way html-to-pdf conversion is handled (encoding html and doing the pdf printing straight up from that as opposed to putting the html into a temporary file and building pdf from that as i used to), or its just my server is being peculiar about chrome nowadays.
