### ISSUE TITLE
Disabling javascript on screenshoted site?

### ISSUE THREAD

**Issue by PayteR** [DaanDeSmedt/PHPHeadlessChrome#18]
Hi, is there any way to disable javascript? It's because I always get cookies bar on pages on sites, thx

**Comment by DaanDeSmedt** [comment]
Having a look at the list of supported flags, can't seem to find any that matches your requirement. [https://peter.sh/experiments/chromium-command-line-switches/](https://peter.sh/experiments/chromium-command-line-switches/).

You can set any additional arguments using the `setArguments(array $arguments)`function if you want to have a try on any of them.
https://github.com/DaanDeSmedt/PHPHeadlessChrome/blob/master/src/HeadlessChrome.php#L88
