### ISSUE TITLE
Wait for web page load

### ISSUE THREAD

**Issue by lucatacconi** [DaanDeSmedt/PHPHeadlessChrome#20]
Hi,
i'm testing PDF production from an html page with a large amount of data loaded by javascript after first html load of the page (ex Simphony o Vue).

By converting my example page to pdf as shown in the example, I only see the raw html without javascript outcome

 is there a way to say PHPHeadlessChrome to wait some seconds o to wait until a selected element is loaded?

**Comment by DaanDeSmedt** [comment]
Hi @lucatacconi ,

You could try using the `--virtual-time-budget` handle to specify a  waiting time budget.


[--virtual-time-budget
](https://chromium.googlesource.com/chromium/src/+/HEAD/headless/app/headless_shell_switches.cc#123)

```
If set the system waits the specified number of virtual milliseconds before deeming the page to be ready. 
For determinism virtual time does not advance while there are pending network fetches (i.e no timers will fire). 
Once all network fetches have completed, timers fire and if the system runs out of virtual time is fastforwarded so the next timer fires immediatley, until the specified virtual time budget is exhausted.
```


Use the [`setArgument($argument, $value)`](https://github.com/DaanDeSmedt/PHPHeadlessChrome/blob/master/src/HeadlessChrome.php#L101) function to include this handle on your Headless Chrome request.
