### ISSUE TITLE
Can you completely remove the HTML path in the PDF?

### ISSUE THREAD

**Issue by richardsonoge** [DaanDeSmedt/PHPHeadlessChrome#23]
There is the HTML path in the PDF convert. So, can you do an update for me to remove it completely for me please? I've attached images of my PDF output so you can understand my issue.

![Screenshot from 2024-08-27 19-48-00](https://github.com/user-attachments/assets/0c632dbc-b061-48f8-ad4c-5aeaf0415200)
![Screenshot from 2024-08-27 19-48-00](https://github.com/user-attachments/assets/d98966d5-d4be-4c39-8771-22238bc50eed)

**Comment by richardsonoge** [comment]
![Screenshot from 2024-08-27 19-48-22](https://github.com/user-attachments/assets/2a720ba9-d80d-46e1-9606-02c116726659)

**Comment by DaanDeSmedt** [comment]
There is an argument available in Chrome : `--no-pdf-header-footer` (or `--print-to-pdf-no-header` for older Chrome versions).
Could you try adding this argument to the `HeadlessChrome `instance?

```php
$headlessChromer = new HeadlessChrome();
$headlessChromer->setArgument('--no-pdf-header-footer', '');
```

**Comment by DaanDeSmedt** [comment]
@richardsonoge  Were you able to give that a try? I'd like to close this issue if possible.

**Comment by DaanDeSmedt** [comment]
Since we haven’t received any updates in a while, I’ll go ahead and close this issue for now due to inactivity. If you still need further assistance, feel free to re-open the issue or create a new one.
