### ISSUE TITLE
how scrape  content & use proxy

### ISSUE THREAD

**Issue by webmarts** [DaanDeSmedt/PHPHeadlessChrome#8]
Hi
I wish to use this library to scrape webpage content, but also wish to use a proxy, so how can I do it

Thanks

**Comment by DaanDeSmedt** [comment]
Hi,

The intend of [PHPHeadlessChrome](https://github.com/DaanDeSmedt/PHPHeadlessChrome) **is not to 'scrape' webpage content** ; but to 'convert' an URL or HTML to PDF / screenshot...

For 'scraping' purpose please refer to ['Goutte' ](https://github.com/FriendsOfPHP/Goutte) ; a simple PHP Web Scraper...
